---
title: "Week 2"
author: "Ducheng Tan"
date: "2026-01-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(astsa)
library(xts)
#View(djia)
```

$$\log (1+r_t) \approx  r_t $$
```{r}
djia_return = diff(log(djia$Close))[-1]
djia_return
par(mfrow= c(2,1))
plot((djia$Close), col = 4)
plot(djia_return, col = 4)



```



$$ r_t = \frac{x_t - x_{t-1}}{x_{t-1}}$$

```{r}

rt_direct = diff(djia$Close)/lag(djia$Close, -1)
cbind(rt_direct, djia_return)
plot(rt_direct)

#The Lag is similar to X_t-1 
```
```{r}
summary(djia_return)
summary(rt_direct)
```




```{R}


par(mfrow=c(2,1))
tsplot(ts(djia_return) ,col="red")
tsplot(ts(rt_direct) ,col="blue")



```
```{r}
d = abs(djia_return - rt_direct)
summary(d)
plot(d)
hist(d)



```
Based on the plots of the d we can see the that the absolute difference is near 0 most of the time. 
Thus we can say 

\begin{equation}
 \log(1+r_t) \approx r_t 
\end{equation}






```{r}
par(mfrow = c(2,1))
w = rnorm(400)

v = filter(w, sides=2, filter=rep(1/5,5))
tsplot(v, col = "tomato")
tsplot(w, col = "black")

```

```{R}


v = filter(w, sides=1, filter = rep(1/4,4))  # Side = 1 means that this is a past average sum 
tsplot(v) 
j = filter(w, sides=2, filter=rep(1,3)) # side = 2 means that this is moving average 
tsplot(j)
```

```{r}
set.seed(90210)
w = rnorm(250 + 50) # 50 extra to avoid startup problems
x = filter(w, filter=c(1.5,-.75),
method="recursive")[-(1:50)]


```

```{r}
x <- 1:10 
y <- filter(x, sides = 2,  filter = rep(c(1,1), 2) , method = "recursive")
y
```

```{r}
set.seed(8675309)
w = rnorm(200)
x = filter(w, filter = 0.55 , method = "convolution")[-(1:100)]
tsplot(x, col= "black")
n = filter(w, filter = 0.55, method = "recursive")[-(1:100)]
tsplot(n, col = "pink")
```

```{r}

w = rnorm(200)
x = filter(w, filter=c(0,.55), method="recursive")[-(1:100)]
v = filter(x, sides=2, filter=rep(1/4,4))


```


```{r}

set.seed(8675309)
w = rnorm(200)
x = filter(w, filter=c(0,.55), method="recursive")[-(1:100)]
v = filter(x, sides=1, filter=rep(1/4,4))
ts.plot(x, lty=2, col=4, ylab="", main="autoregression + moving average")
lines(v, col = 6)
legend(0, -2.5, lty=c(2,1), lwd=2, col=c(4,6), bg="white",
legend=c("x_t (autoregression)", "v_t (moving average of x_t)"))







```


```{r}
set.seed(8675309)
w = rnorm(200)
x = filter(w, filter=c(0,.55), method="recursive")[-(1:100)]
v = filter(x, sides=1, filter=rep(1/4,4))
tsplot(x, lty=2, col=4, ylab="", main="autoregression + moving average")
lines(v, col=6)
legend(0, -2.5, lty=c(2,1), lwd=2, col=c(4,6), bg="white",
legend=c("x_t (autoregression)", "v_t (moving average of x_t)"))

```

