---
title: "Week 2"
author: "Ducheng Tan"
date: "2026-01-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(astsa)
library(xts)
library(stats)
#View(djia)
```

$$\log (1+r_t) \approx  r_t $$
```{r}
djia_return = diff(log(djia$Close))[-1]
djia_return
par(mfrow= c(2,1))
plot((djia$Close), col = 4)
plot(djia_return, col = 4)



```



$$ r_t = \frac{x_t - x_{t-1}}{x_{t-1}}$$

```{r}
 rt_direct = diff(djia$Close)/lag(djia$Close, -1)
cbind(rt_direct, djia_return)
plot(rt_direct)


#The Lag is similar to X_t-1 
```




```{R}


difference <- rt_direct - djia_return 
difference <- na.omit(difference)
mean(difference)


```
We can perform $\chi^2 -$ test and $t-$ test to compare the standard deviation and mean. 







```{r}
w = rnorm(400)
tsplot(w)
v = filter(w, sides=2, filter=rep(1/5,5))
tsplot(v)
```
```{R}

set.seed(90210)
w = rnorm(250 + 50) # 50 extra to avoid startup problems
x = filter(w, filter=c(1.5,-.75),
method="recursive")[-(1:50)]
```

```{r}
x <- 1:10 
y <- filter(x, filter = c(1,1), method = "recursive")


```

```{r}
#1c.3a
set.seed(78)
w <- rnorm(200)
#1c.3b
x<- filter(w, filter =c(0,.55), method="recursive")[-(1:100)]
tsplot(x,col="blue")

```
```{r}
v <- filter(x, sides = 1, filter = rep(1/4,4) )

tsplot(v, col="red")
```

```{r}
ts.plot(x,v, lty = c(2,1), col= c("blue", "red"),  main="Regression vs Past Average",
        ylab = "values")
legend("topright", legend=c("x", "v"), lty =c(2,1), col=c(5,2))


```
